######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "D:/zybo_home/zybo_home.srcs/sources_1/edk/module_1"
if { [xload new module_1.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z010
xset package clg400
xset speedgrade -1

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
